name: Simple Contexts Example
on: push
jobs:
  print-info:
    runs-on: ubuntu latest
    steps:
      - name: Set custom environment variable
        run: echo "CUSTOM_VARIABLE=Hello, World!" >> $GITHUB_ENV

      - name: Print commit author and custom environment variable
        run: |
          echo "Commit author: ${{ github.actor }}"
          echo "Custom variable: ${{ env.CUSTOM_VARIABLE }}"
